### ISSUE TITLE
Add and use tokenlists

### ISSUE THREAD

**Issue by 0xonramp** [IndexCoop/flash-mint-sdk#56]
Add the tokenlists dependency and replace address literals in the code.

## TODOs
- [x] remove all uses of `QuoteTokens` - except `eth`; check some newer tests for reference
- [x] `ETH` could be used from `constants/tokens` as well; probably better?
- [x] replace all uses of token constants. how? just use tokenlists utility functions?

**Comment by janndriessen** [comment]
Should now be done once the new tokenlist (v2) is in production. Potentially, still a big refactoring tho.
